### ISSUE TITLE
FEATURE: Read and resource cards on sidebar of reads and resources slug page

### ISSUE THREAD

**Issue by davidcjanssens** [excelerate-america/ea-features#129]
Goal: To be able 1 to 1 reference a resource to a read and a read to a resource.

### Requirements:
- Content team can connect a read to a resource so that on resource slug the read card is shown on sidebar
- Content team can connect a resource to a read so that on read slug the resource card is shown on sidebar
- Sidebar resources still need membership to go to slug page and thus should go to custom onboarding

**On Reads/slug Page Sidebar:**
- Default cards: Share Card, Author Card
- Optional cards (Max 2 Cards can be added, one from each kind): Discord Channel Card, Resource Card, Event Card 
- Weight Rank: Author Card > Share Card > Discord Channel Card > Resource Card > Event Card

**On Resources/slug Page Sidebar:**
- Default card: Share Card
- Optional card: Reads Card

### Design Files
[Figma Handoff for Sidebar Items](https://www.figma.com/file/WcomKJ8a26WaxzPHnd3TNS/PAGE%3A-events%2Fslug-%26-PAGE%3A-reads%2Fslug-Add-items-on-the-sidebar?node-id=42%3A1535)
This file contains
- Resources/Slug with Sidebar
- Reads/Slug with Sidebar
- Responsive views

**Comment by davidcjanssens** [comment]
@youngmin-ea do we have designs for this you can reference?

**Comment by youngmin-ea** [comment]
Design is ready so moved to `In Dev` @davidcjanssens

**Comment by tech-ea** [comment]
@davidcjanssens I'm not sure when you edited / added to this issue can you please check out issue  #11 because I rolled this functionality into that issue, but if i missed something please amend.
