### ISSUE TITLE
Refactoring of events

### ISSUE THREAD

**Issue by tech-ea** [excelerate-america/ea-features#14]
## Refactoring of events
- [x] #30
- [x] #31
- [x] #32
- [x] #33
[See Discussion](https://github.com/excelerate-america/ea-ecosystem/discussions/183#discussion-4099742

~~ **this is not possible as of currently** Add User to discord event on app RSVP~~
~~Test Brainstorm and One on One capability post recent updates~~ (Requires a complete rework of events and their data structures )

GanttStart: 2022-06-27
GanttDue: 2022-07-14

**Comment by tech-ea** [comment]
@lyndon-bot This list of tasks under `Refactoring of Events` is just the start. Ideally, this issue should be edited to reflect all the underlying tasks. Then we can convert the checkbox bullet points to actual issues and assign and track accordingly.

**Comment by bandhanEA** [comment]
Testing on staged: 
1. Create event on Discord without an image/description 
2. Add slug and image on hyGraph and save 
3. Check if save is still in Draft mode 
4. Publish event and check if event is published 
5. Make an edit on a field and re-publish event and check if event is published 
6. Update event on Discord and check if event is published

**Comment by davidcjanssens** [comment]
@lyndon-bot can we close this?
