### ISSUE TITLE
HUBSPOT Transfer

### ISSUE THREAD

**Issue by tech-ea** [excelerate-america/ea-features#24]
### Objective:
- move contacts and landing pages from Hubspot to new site / bigquery

- [x] #25
- [x] #26
- [x] #27
- [x] #28
- [x] #29

## TRANSFER PROCESS
- Get CSv
- Remove Duplicate Column Names / create schema
- Upload CSV to Storage
- Create table from CSV file in storage in BigQuery

### Notes:
- Duplicate column 'Company_name' for table 'csv_sample_100_433c419b_f6ba_41a7_937c_f8d064623cc5_source'.
- Duplicate column 'Days_to_Close' for table 'csv_sample_100_433c419b_f6ba_41a7_937c_f8d064623cc5_source'.

### Files:
[DRIVE](https://drive.google.com/drive/folders/1M0EIC_5jBEJcGupc-ACe_4fk8HqLu16o?usp=sharing)

### Services;
[GCP Bucket](https://console.cloud.google.com/storage/browser/eagdl-ea-dump;tab=objects?forceOnBucketsSortingFiltering=false&project=ea-great-data-lakes&prefix=&forceOnObjectsSortingFiltering=false)
[GCP BigQuery](https://console.cloud.google.com/bigquery?project=ea-great-data-lakes)

## Reference:
nextjs and subdomains
https://vercel.com/support/articles/can-i-redirect-from-a-subdomain-to-a-subpath

**Comment by bandhanEA** [comment]
Affiliate Billing Contacts: 
![Screen Shot 2022-07-28 at 12 11 14 PM](https://user-images.githubusercontent.com/88337150/181586723-7bdefec2-0183-4798-bc5b-214a0a6e0421.png)
![Screen Shot 2022-07-28 at 12 11 26 PM](https://user-images.githubusercontent.com/88337150/181586733-ae2a4978-a77c-44b3-bd07-0dc949bc8f9d.png)

![Screen Shot 2022-07-28 at 12 11 36 PM](https://user-images.githubusercontent.com/88337150/181586744-01000db3-64b1-4b8d-a7ec-d8960c3f74ae.png)
