### ISSUE TITLE
FEATURE: RESOURCE List and Slug

### ISSUE THREAD

**Issue by tech-ea** [excelerate-america/ea-features#5]
### REQUIREMENTS

P0

- [x] Resource index page that has multiple sections of resources card a public or member can scroll
- [x] Public member when clicking on resource will be re-routed to a custom onboarding for resources
- [x] Resources will be placed in section categories (Marketing, Team Development, Personal Growth, Finances and Funding, and Local Partners)
- [x] Each Resource will have a card that links to a slug page for that resource and includes a title, short description and attribution to any partner who contributed to the resource (ie Score, IDEO, ZipRecruiter)
- [x] Each Resource slug page will have a Headline, description, how to use it section, download CTA or link and reference
- [x] Resources will have universal tags similar to events and reads
- [x] Downloaded resources can come from a Google Drive folder

P1

- [ ] Members can "like" a resource on the resource slug and this will increase the total "likes" on slug page and card
- [ ] Resource slug page sidebar can have a read or discord channel card connected to it
- [ ] Resources can be sorted by tags and not just sections
- [ ] Resource cards can be put on sidebar of a Read or Event
- [ ] Resource cards can have a section on homepage, if clicked will send to custom onboarding

### Design Files
- [Figma Handoff File](https://www.figma.com/file/DHd7uRMBbJPPfoCeVLu3wQ/Page%3A-Resources%2Findex-%26-%2Fslug?node-id=1226%3A3903)
- [Resource Card Component link](https://www.figma.com/file/c71dkFLXe4L3ZNlKX3GMeA/Design-Library-for-Storybook-Setup?node-id=4108%3A9270)
- [Matching UI with Hygraph Fields (Created by Emily S)](https://www.figma.com/file/DHd7uRMBbJPPfoCeVLu3wQ/Page%3A-Resources%2Findex-%26-%2Fslug?node-id=1503%3A5932)

### REFERENCES
- [Resource Spreadsheet](https://docs.google.com/spreadsheets/d/1K-0vSeKpYZSOqUgSgB1n08vAoziMKrIGtMvpmRmDBu4/edit?usp=sharing)

#### General 
- **resourceName** String Single line text Required Title
- **resourceSlug** String Slug Unique
- **resourceCategory** String Single line text Required
- **resourceTags** Multiple Values Dropdown 
- **isFeatured** Boolean required

#### Card

- **resourceSource** String Single line text
- **resourceCardTitle** String Single line text
- **resourceCardSubtitle** String Single line text
- ~~resourceCopy~~ --> **resourceCardCopy** String Multi line text

### Slug
- **resourceHeadline** String Markdown
- **resourceSubheadline** String Markdown
- ~~resourceDescription~~ --> **resourceRichText** RichText
- **timeToComplete** String Single line text
- **panels** ContentPanel, QuotePanel Multiple Values
- **resourceCtaLink** String Single line text (HTML slug)
- **resourceCtaLabel**
- **resourceSourceUrl**
- **resourceImage** media

**New components**
- [x] #81
- [x] #82
- [x] #83
- [x] #84
- [x] #85
- [x] excelerate-america/design-system-eax#198
- [x] excelerate-america/design-system-eax#197

GanttStart: 
GanttDue:

**Comment by davidcjanssens** [comment]
@youngmin-ea added the user reactions to this as P1

**Comment by youngmin-ea** [comment]
@tech-ea @sorengrey Resources page P0 design is handoff. Responsive views are included on the same page in Figma

**Comment by tech-ea** [comment]
@emilyschlicter added spreadsheet link to this issue

**Comment by emilyschlicter** [comment]
started a new figma (based off youngmin's) showing the ui with the actual field names in hygraph 
https://www.figma.com/file/DHd7uRMBbJPPfoCeVLu3wQ/Page%3A-Resources%2Findex-%26-%2Fslug?node-id=1503%3A5932
