### ISSUE TITLE
FEATURE: Community Partner Link Builder,   Landing Page, and Custom ONBOARD Pathway

### ISSUE THREAD

**Issue by tech-ea** [excelerate-america/ea-features#7]
## Community Partner ONBOARD Process
- What is a Group?
- What is a Promo
What are the plans

## APP
- [ ] REQUIRES: `CUSTOM ONBOARD PATHWAY` with QUERY PARAMTERS
- [ ] Requirements for a Community Parter Onboard (on App, on Discord?)
- [ ] Create `PARTNER_CODE` and Connect with Community Partner
- [ ] Use `PARTNER_CODE` to build Link 
- [ ] Share Link with Community Partner

## DISCORD
- [ ] Discord Permissions
- [ ] Partner Events?

### ADMIN
- [ ] Track / Monitor members based on `PARTNER_CODE` (ADMIN)

### RESOURCES
[Diagram of Collections](https://drive.google.com/file/d/1P1Lktor8gjP-7RXqX_yOrkucPpnxUb1u/view?usp=sharing)

GanttStart:
GanttDue:

**Comment by davidcjanssens** [comment]
Roy asked the question if we could place a Partner Field into a Private profile?  @tech-ea @lyndon-bot

**Comment by tech-ea** [comment]
@davidcjanssens a partner code will be saved to the member's profile. 
How this code is generated and how it is connected still seems unclear.
There was talk of expiration of code... which would require more than a single code.
probably.
partnerCode: (unique to a single partner)
partnerPromoCode: (limited to a date range)

**Comment by davidcjanssens** [comment]
I think if the scope is not large, it makes sense for us to create an ability to do the following:

1.) Create a partnerCode for a new partner (ie Chamber of Tempe)
2.) Create a PromoCode for a new promotion (ie 1 year trial) with a date range

These two codes could be put together but could also be seperate.

Example 1
For a Community Partner New Member Drive, we would need to create partner Code (if not already a partner) AND a promocode for 1 year trial with date range of Sept 1 - Sept 30

Example 2
For a ODP New or existing express customer, we send a link to get a lifetime trial of Plus.  This would need a 
"partnerCode = ODP and a promocode for lifetime trail with date range of Jan 1 - Dec 31 (or whatever)

This tells me that a member could have more than one partner code (or Group ID).  As a member from chamber of tempe could also become an ODP Express Account

This also tells me PartnerCode = GroupID.  And be more generic for us.  We could use it for sending/tracking/converting specific promos.

But we also could Group ID= 

Put users into a cohort = Gamechangers 
Show/hide certain events depending on Group ID
Send emails to lists only with certain Group IDs
Give Roles in Discord to only certain Group IDs to make channels or set certain permissions
Use Group ID as another way to track where members came from (Community partner X, ODP Express lead, etc)
User Group ID to create "interest groups" based on profile information selected.  This could allow us to adapt dashboards/my home or weekly emails to more tailored selections.  

We also need an ability to make and mgmt Group IDs and promo Codes. 

- Heidi/Esther/Emily need to be able to create a new Group.  
- Heidi/Esther/Emily need to be able to create a promo that selects a trial (1 year or lifetime)


As a P1 to Profile:
We should show what groups a person is in.  This can be just be a list view with limited info.

**Comment by davidcjanssens** [comment]
@lyndon-bot @tech-ea @youngmin-ea See above

**Comment by tech-ea** [comment]
So it looks like groups & promos.

GROUPS
```
groupId: (unique id)
groupName: ???
groupType: 
groupDetails:

```
PROMOS
```
promoCode: (unique id)
promoName: ???
promoType: 
promoDetails:
promoStart: DateTime
promoEnd: DateTime
groupId: uniqueGroupId
```

url could be: 
`/onboard/partner-default/start?groupId=codeforgroup&promoCode=uniquepromocode`

@davidcjanssens  @youngmin-ea @lyndon-bot

**Comment by tech-ea** [comment]
@lyndon-bot When you can we should talk about groups. I saw you updated the diagram.
I'd like to know  your reasoning behind having groups array / subcollection on member, discordAccount , and busnessAccount docs

**Comment by tech-ea** [comment]
Closing thi sissue refer to #127
