### ISSUE TITLE
TOOL: HyGraph GraphQL Management Tool

### ISSUE THREAD

**Issue by tech-ea** [excelerate-america/ea-features#80]
## HyGraph GraphQL Management Tool

- [x] #118
- [x] #119
- [x] #120
- [x] #121
- [x] #122

**Comment by emilyschlicter** [comment]
![Screen Shot 2022-08-16 at 8 49 58 AM](https://user-images.githubusercontent.com/97050328/184897077-c1aabd7c-26c6-41b5-b837-53738242c761.png)

![Screen Shot 2022-08-16 at 8 50 08 AM](https://user-images.githubusercontent.com/97050328/184897046-0e6bec67-908b-4887-8ad7-25a3cbaf01c2.png)
